[package]
name = "tough"
version = "0.1.0"
description = "The Update Framework (TUF) repository client"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/awslabs/tough"
keywords = ["tuf", "update", "repository"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
hex = "0.3.2"
reqwest = { version = "0.9.17", default-features = false }
serde = "1.0.92"
serde_json = "1.0.39"
sha2 = "0.8.0"
snafu = "0.5.0"
tough_schema = { version = "0.1.0", path = "../tough_schema" }

[dev-dependencies]
hex-literal = "0.2.0"

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
default-tls-vendored = ["reqwest/default-tls-vendored"]
rustls-tls = ["reqwest/rustls-tls"]
