name: Rust
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo fmt -- --check
    - run: cargo clippy --locked -- -D warnings
    - run: cargo build --locked
    - run: cargo test --locked
